/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2019-2021 Trusted Objects. All rights reserved.
 */

/**
 * @file asn1.h
 * @brief ASN1 constants.
 */

#ifndef _TO_ASN1_H_
#define _TO_ASN1_H_

#include "TO_defs.h"

#define TO_ASN1_PATTERN_COMMON_NAME_LEN		3
#define TO_ASN1_PATTERN_SECP256R1_LEN		8
#define TO_ASN1_PATTERN_ECDSAWITHSHA256_LEN	8
#define TO_ASN1_PATTERN_ECPUBLICKEY_LEN		7
#define TO_ASN1_PATTERN_AKI_LEN			3
#define TO_ASN1_PATTERN_SKI_LEN			3

#define TO_ASN1_PUBKEY_SIZE (2UL + 2UL + 64UL)
#define TO_ASN1_PRIVKEY_MINSIZE (2UL + 3UL + 2UL + 2UL \
		+ TO_ASN1_PATTERN_ECPUBLICKEY_LEN + 2UL \
		+ TO_ASN1_PATTERN_SECP256R1_LEN + 2UL + 2UL + 3UL + 2UL \
		+ TO_ECC_PRIV_KEYSIZE - 1)
#define TO_ASN1_PRIVKEY_MAXSIZE (TO_ASN1_PRIVKEY_MINSIZE + 1UL)
#define TO_ASN1_SIGNATURE_MAXSIZE (2UL + 64UL + (2UL * 3UL))
#define TO_ASN1_AKI_SIZE (2UL + 2UL + 2UL + 20UL)
#define TO_ASN1_SKI_SIZE (2UL + 2UL + 20UL)
#define TO_ASN1_SIGNATURE_ALG_SIZE (2UL + 2UL + TO_ASN1_PATTERN_ECDSAWITHSHA256_LEN)
#define TO_ASN1_PUBKEY_ALG_SIZE (2UL + 2UL + TO_ASN1_PATTERN_ECPUBLICKEY_LEN + 2UL + TO_ASN1_PATTERN_SECP256R1_LEN)

#define TO_ASN1_CSR_VERSION_SIZE 3UL
#define TO_ASN1_CSR_EXT_SIZE 2UL
#define TO_ASN1_CSR_MAXSIZE (4UL + 4UL + TO_ASN1_CSR_VERSION_SIZE + TO_CERT_DN_MAXSIZE + 2UL + TO_ASN1_PUBKEY_ALG_SIZE + TO_ASN1_PUBKEY_SIZE + TO_ASN1_CSR_EXT_SIZE + TO_ASN1_SIGNATURE_ALG_SIZE + 3UL + TO_ASN1_SIGNATURE_MAXSIZE)

#endif /* _TO_ASN1_H_ */

