/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2022-2023 Trusted Objects. All rights reserved.
 */

/**
 * Data below depends on TO-Protect binary delivery, and should not be edited
 * by hand.
 */

#ifndef _TOP_INFO_H_
#define _TOP_INFO_H_

/* TO-Protect Secure Storage footprints */
#define TOP_SECURE_STORAGE_NVM_FOOTPRINT 8192u
#define TOP_SECURE_STORAGE_RAM_FOOTPRINT 8192u

/* Some TO-Protect build constants */
#define TOP_CERT_X509_MAXSIZE 1024u

#endif // _TOP_INFO_H_
