/*
 * THIS SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * Copyright (C) 2022-2023 Trusted Objects. All rights reserved.
 */

/**
 * Data below depends on TO-Protect binary delivery, and should not be edited
 * by hand.
 */

#ifndef _TOP_TECHNICAL_INFO_H_
#define _TOP_TECHNICAL_INFO_H_

/* TO-Protect RAM data size */
#define TOP_RAM_DATA_SIZE 6012u

/* TO-Protect Secure internal context size */
#define TOP_INTERNAL_CTX_SIZE 112u

#endif // _TOP_TECHNICAL_INFO_H_
